SELECT * FROM USERS
SELECT * FROM PHOTOS
SELECT * FROM LIKES
SELECT * FROM COMMENTS
SELECT * FROM FOLLOWS
SELECT * FROM TAGS
SELECT * FROM PHOTO_TAGS

/* GETTING THE OLDEST USERS FROM OUR INSTAGRAM DATABASE AND LIMITING BY 2*/
SELECT  * FROM USERS
ORDER BY created_at
LIMIT 2;
