SELECT * FROM USERS
SELECT * FROM PHOTOS
SELECT * FROM LIKES
SELECT * FROM COMMENTS
SELECT * FROM FOLLOWS
SELECT * FROM TAGS
SELECT * FROM PHOTO_TAGS

/* GETTING THE OLDEST USERS FROM OUR INSTAGRAM DATABASE AND LIMITING BY 2*/
SELECT  * FROM USERS
ORDER BY created_at
LIMIT 2;

/*GETTING INACTIVE USERS FROM OUR DATABASE*/
SELECT USERNAME
FROM USERS
LEFT JOIN photos ON users.id=photos.user_id
WHERE photos.id IS NULL;

/*GETTING THE MOST ACTIVE USERS FROM THE DATABASE*/

SELECT users.username, COUNT(photos.image_url)
FROM USERS
JOIN photos ON users.id=photos.user_id
GROUP BY users.id
ORDER BY 2 DESC;