
/*COMMENTS TABLE CREATION*/
CREATE TABLE COMMENTS(
id SERIAL PRIMARY KEY,
Comment_text VARCHAR(255),
Photo_id INT NOT NULL,
User_id INT NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
FOREIGN KEY(user_id) REFERENCES Users(id),
FOREIGN KEY(Photo_id) REFERENCES Photos(id)
);
