/*CREATING TABLES*/
CREATE TABLE PHOTO_TAGS(
 PHOTO_id INT NOT NULL,
 TAG_id  INT  NOT NULL,
 FOREIGN KEY(PHOTO_id) REFERENCES PHOTOS(id),
 FOREIGN KEY(TAG_id) REFERENCES TAGS(id),
 PRIMARY KEY(PHOTO_id,TAG_id)
);